### ISSUE TITLE
Player object error

### ISSUE THREAD

**Issue by R4ve69** [toxicrecker/DiscordUtils#13]
After reading the docs, trying on my own, and constantly getting errors I decided I would try your code but it gave the same error. Whenever I use the player it says TypeError: 'NoneType' object is not subscriptable or when I use the volume command it says 'NoneType' object has no attribute 'change_volume'. I'm using python 3.8 because I had an error installing with 3.9

**Comment by toxicrecker** [comment]
The `get_player` method returns `None` if the player is not found, so you would first need to create a player using `create_player` method so that it returns a player object.
