### ISSUE TITLE
Pagination - Commands should work when removing reactions aswell.

### ISSUE THREAD

**Issue by NachoCasta** [toxicrecker/DiscordUtils#14]
Right now, if you want to use the same command twice in a row you have to react, unreact and react again.
The bot should also wait for remove_reaction aswell.

**Comment by zboggert** [comment]
> Right now, if you want to use the same command twice in a row you have to react, unreact and react again.
> The bot should also wait for remove_reaction aswell.

Thats what remove_reactions=True is for

**Comment by isaa-ctaylor** [comment]
> Right now, if you want to use the same command twice in a row you have to react, unreact and react again.
> The bot should also wait for remove_reaction aswell.

I agree, if the bot doesn't have manage_messages perms for whatever reason, then it can't remove the reaction

**Comment by toxicrecker** [comment]
Thanks for the suggestion, I will be implementing this in future updates
