### ISSUE TITLE
Invite Tracker - KeyError: guild.id

### ISSUE THREAD

**Issue by R4ve69** [toxicrecker/DiscordUtils#17]
When A user joines the guild and the on_member_join event runs, whenever it gets to` inviter = await tracker.fetch_inviter(member)` then it says Keyerror: {guild.id}

Is there something I should do or is it a problem with DiscordUtils?

**Comment by NightZan999** [comment]
> When A user joines the guild and the on_member_join event runs, whenever it gets to` inviter = await tracker.fetch_inviter(member)` then it says Keyerror: {guild.id}
> 
> Is there something I should do or is it a problem with DiscordUtils?

hmmm, KeyError, that means in a dictionary there is some key which is not even found. Show your entire code please?

**Comment by toxicrecker** [comment]
Its a cache issue, make sure you use all the caching methods and your bot has manage server permissions
