### ISSUE TITLE
Unnecessary heavy dependencies should not be compulsory

### ISSUE THREAD

**Issue by anand2312** [toxicrecker/DiscordUtils#24]
The title says it all; `youtube_dl` and `discord.py[voice]` are not dependencies that everyone needs. They should not be compulsory installs with this, when someone just wants to use, say the paginator or the invite tracker.

They should be made into optional installs, that users could _choose_ to install.

**Comment by JayDwee** [comment]
@anand2312 try installing now with `pip install DiscordUtils` and it should load without voice support (and not require voice dependencies)
