### ISSUE TITLE
 Command raised an exception: KeyError: 'dislike_count'

### ISSUE THREAD

**Issue by Abbhiishek** [toxicrecker/DiscordUtils#39]
Command raised an exception: KeyError: 'dislike_count'

**Comment by amirdadfar9192** [comment]
yeah i have the same problem . apparently youtube removed dislike_count on their api so we can no longer get the dislike_count and this module uses a function that gets all the information in youtube including dislike_count something we cant get. we can do nothing but to wait for them to change their code.

**Comment by zen1405** [comment]
You can go to the file Music.py where you get the error and comment out the dislikes
![dislike](https://user-images.githubusercontent.com/37182124/144728806-6c30b9bb-dde3-443b-9cdb-9142f2f4d9bd.png)

This is just a temporary fix till DiscordUtils fixes it. Hope it helps

**Comment by Abbhiishek** [comment]
Yeah commenting out can be a solution ! since we don't need dislike count .

**Comment by MysteriousK69** [comment]
Wouldn't just removing dislike count be a permanent solution? Because Youtube does not show dislikes anymore.

**Comment by amirdadfar9192** [comment]
yep it will and i did a pull request on it but Contributors apparently aren't very active here i did a pull request on it but they didn't check it YET

**Comment by zen1405** [comment]
> Wouldn't just removing dislike count be a permanent solution? Because Youtube does not show dislikes anymore.

Yeah, I still would keep it as a comment in case youtube does reroll the dislikes back, doesn't hurt either way.

**Comment by MysteriousK69** [comment]
@amirdadfar9192 I will ask him to check it lol

**Comment by amirdadfar9192** [comment]
thanks haha

**Comment by MysteriousK69** [comment]
Update: he said he doesn't maintain the repo anymore

**Comment by MysteriousK69** [comment]
Yeah, he abandoned it. And idk if anyone else has perms.

**Comment by amirdadfar9192** [comment]
ok.i respect the owner, i will publish his code OBVIOUSLY WITH HIS CREDITS AND NAME FOR THE CODE . in pypi so we can still use this module

**Comment by amirdadfar9192** [comment]
if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
i just commented the dislike lines and the code is still for toxicrecker

**Comment by Abbhiishek** [comment]
> if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod i just commented the dislike lines and the code is still for toxicrecker

Hey i want to know how to create pakages like this that others can import and use ?

**Comment by amirdadfar9192** [comment]
> > if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod i just commented the dislike lines and the code is still for toxicrecker
> 
> Hey i want to know how to create packages like this that others can import and use ?

just code your project then when its ready you can use pypi and their docs to publish it on pypi . when its there everyone can install it by pip commands.https://pypi.org/help/#publishing

**Comment by DTS-11** [comment]
> if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
> i just commented the dislike lines and the code is still for toxicrecker

is the installation using git? or is it on pypi?

**Comment by amirdadfar9192** [comment]
> > if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
> > i just commented the dislike lines and the code is still for toxicrecker
> 
> is the installation using git? or is it on pypi?

you can install it as a python module with pypi

**Comment by DTS-11** [comment]
> > > if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
> > > i just commented the dislike lines and the code is still for toxicrecker
> > 
> > is the installation using git? or is it on pypi?
> 
> you can install it as a python module with pypi

`pip install DiscordUtilsMod` ?

**Comment by amirdadfar9192** [comment]
> > > > if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
> > > > i just commented the dislike lines and the code is still for toxicrecker
> > > 
> > > 
> > > is the installation using git? or is it on pypi?
> > 
> > 
> > you can install it as a python module with pypi
> 
> `pip install DiscordUtilsMod` ?

yup :)

**Comment by amirdadfar9192** [comment]
> > > > > > if any one want to use it for thier bots you can use this.https://github.com/amirdadfar9192/DiscordUtilsMod
> 
> this only works with discord.py according to the setup.py, other forks like nextcord, pycord won't work

i did another project for nextcord

https://pypi.org/project/nextcordutils/

**Comment by DTS-11** [comment]
> i did another project for nextcord
> https://pypi.org/project/nextcordutils/

I'm using pycord
