### ISSUE TITLE
NameError: name 'ctx' is not defined

### ISSUE THREAD

**Issue by ReyterYT** [toxicrecker/DiscordUtils#6]
Line 119 on Paginations.py
i found this on the code![Screenshot_2020-11-01-14-33-50-70.png](https://user-images.githubusercontent.com/59440735/97797410-66587780-1c4f-11eb-8f60-8fdc1dee04e2.png)
im thinking your supposed to use self.ctx.author instead of ctx.author
![Screenshot_2020-11-01-14-35-35-74.png](https://user-images.githubusercontent.com/59440735/97797426-84be7300-1c4f-11eb-83d4-63f4e8fc30ad.png)

**Comment by Taromaruu** [comment]
Check my pull request for the fix @ReyterYT

**Comment by scrazzz** [comment]
This issue has been fixed. Install the latest update.

**Comment by ReyterYT** [comment]
> This issue has been fixed. Install the latest update.

seems to not work im currently on version 1.2.3. Same issue

**Comment by toxicrecker** [comment]
this issue has been fixed please make sure that you're on version 1.2.3
